apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
  {{- include "todo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "todo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "todo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todo.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.storage.containerPath }}
              name: db-pv-storage
          env:
            - name: CONNECTION_STRING
              value: "{{ .Values.storage.containerPath }}/{{ .Values.db.sqliteDbFilename }}"
            - name: HOST_ADDRESS
              value: "{{ .Values.app.host }}:{{ .Values.app.port }}"
            - name: DB
              value: "{{ .Values.db.type }}"
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 5
            httpGet:
              path: /live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /ready
              port: http
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          command: ["/todo-api"]
          args: ["--db", "$(DB)"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
