apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql-port
      protocol: TCP
      name: mysql-port
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
